// <auto-generated />
using System;
using IPR_BE.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IPR_BE.Migrations
{
    [DbContext(typeof(TestReportDbContext))]
    [Migration("20230718190341_initial-test-models")]
    partial class initialtestmodels
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CandidateSkill", b =>
                {
                    b.Property<int>("Candidateid")
                        .HasColumnType("int");

                    b.Property<int>("Skillid")
                        .HasColumnType("int");

                    b.HasKey("Candidateid", "Skillid");

                    b.HasIndex("Skillid");

                    b.ToTable("CandidateSkill");
                });

            modelBuilder.Entity("IPR_BE.Models.Candidate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("currentRole")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("currentRole");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("candidateEmail");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("candidateName");

                    b.Property<int?>("yearsExperience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("yearsExperience");

                    b.HasKey("id")
                        .HasName("id");

                    b.ToTable("Candidates", (string)null);
                });

            modelBuilder.Entity("IPR_BE.Models.InterviewBotLog", b =>
                {
                    b.Property<int>("logId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("logId"));

                    b.Property<DateTime>("created")
                        .HasColumnType("datetime2");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("logId")
                        .HasName("logId");

                    b.ToTable("InterviewBotLogs", (string)null);
                });

            modelBuilder.Entity("IPR_BE.Models.Question", b =>
                {
                    b.Property<long>("questionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("questionId"));

                    b.Property<int>("possiblePoints")
                        .HasColumnType("int");

                    b.Property<string>("prompt")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("questionTypeId")
                        .HasColumnType("int");

                    b.HasKey("questionId");

                    b.ToTable("Questions");
                });

            modelBuilder.Entity("IPR_BE.Models.QuestionType", b =>
                {
                    b.Property<int>("questionTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("questionTypeId"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("questionTypeId");

                    b.ToTable("QuestionTypes");
                });

            modelBuilder.Entity("IPR_BE.Models.Skill", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("IPR_BE.Models.Tag", b =>
                {
                    b.Property<long>("tagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("tagId"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("tagId");

                    b.ToTable("Tags");
                });

            modelBuilder.Entity("IPR_BE.Models.Test", b =>
                {
                    b.Property<long>("testId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("testId"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("testId");

                    b.ToTable("Tests");
                });

            modelBuilder.Entity("IPR_BE.Models.TestAttempt", b =>
                {
                    b.Property<long>("attemptId")
                        .HasColumnType("bigint");

                    b.Property<int>("candidateId")
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("createdOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("endDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("invitationUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("startDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<long>("testId")
                        .HasColumnType("bigint")
                        .HasColumnName("testId");

                    b.Property<int>("totalScore")
                        .HasColumnType("int");

                    b.HasKey("attemptId")
                        .HasName("attemptId");

                    b.HasIndex("candidateId");

                    b.ToTable("TestAttempts", (string)null);
                });

            modelBuilder.Entity("IPR_BE.Models.TestAttemptQuestionSection", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<int>("autoScore")
                        .HasColumnType("int");

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("manualScore")
                        .HasColumnType("int");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("testAttemptSectionId")
                        .HasColumnType("bigint");

                    b.Property<long>("testQuestionId")
                        .HasColumnType("bigint");

                    b.Property<int>("timeViolation")
                        .HasColumnType("int");

                    b.Property<int>("windowViolation")
                        .HasColumnType("int");

                    b.HasKey("id");

                    b.ToTable("TestAttemptQuestionSections");
                });

            modelBuilder.Entity("IPR_BE.Models.TestAttemptSection", b =>
                {
                    b.Property<long>("testAttemptSectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("testAttemptSectionId"));

                    b.Property<string>("comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("testAttemptId")
                        .HasColumnType("bigint");

                    b.Property<long>("testSectionId")
                        .HasColumnType("bigint");

                    b.HasKey("testAttemptSectionId");

                    b.ToTable("TestAttemptSections");
                });

            modelBuilder.Entity("IPR_BE.Models.TestSection", b =>
                {
                    b.Property<long>("testSectionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("testSectionId"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<long>("testId")
                        .HasColumnType("bigint");

                    b.HasKey("testSectionId");

                    b.ToTable("TestSections");
                });

            modelBuilder.Entity("IPR_BE.Models.TestSectionQuestion", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<long>("questionId")
                        .HasColumnType("bigint");

                    b.Property<long>("testSectionId")
                        .HasColumnType("bigint");

                    b.HasKey("id");

                    b.ToTable("TestSectionQuestions");
                });

            modelBuilder.Entity("IPR_BE.Models.TestTag", b =>
                {
                    b.Property<long>("testTagId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("testTagId"));

                    b.Property<long>("tagId")
                        .HasColumnType("bigint");

                    b.Property<long>("testId")
                        .HasColumnType("bigint");

                    b.HasKey("testTagId");

                    b.ToTable("TestTags");
                });

            modelBuilder.Entity("CandidateSkill", b =>
                {
                    b.HasOne("IPR_BE.Models.Candidate", null)
                        .WithMany()
                        .HasForeignKey("Candidateid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IPR_BE.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("Skillid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IPR_BE.Models.TestAttempt", b =>
                {
                    b.HasOne("IPR_BE.Models.Candidate", null)
                        .WithMany()
                        .HasForeignKey("candidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
