// <auto-generated />
using System;
using IPR_BE.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace IPR_BE.Migrations
{
    [DbContext(typeof(TestReportDbContext))]
    [Migration("20230727200143_manual-grade-data-type")]
    partial class manualgradedatatype
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CandidateSkill", b =>
                {
                    b.Property<int>("Candidateid")
                        .HasColumnType("int");

                    b.Property<int>("Skillid")
                        .HasColumnType("int");

                    b.HasKey("Candidateid", "Skillid");

                    b.HasIndex("Skillid");

                    b.ToTable("CandidateSkill");
                });

            modelBuilder.Entity("IPR_BE.Models.Candidate", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("currentRole")
                        .HasColumnType("varchar(255)")
                        .HasColumnName("currentRole");

                    b.Property<string>("email")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("candidateEmail");

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("varchar(255)")
                        .HasColumnName("candidateName");

                    b.Property<int?>("yearsExperience")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0)
                        .HasColumnName("yearsExperience");

                    b.HasKey("id")
                        .HasName("id");

                    b.ToTable("Candidates", (string)null);
                });

            modelBuilder.Entity("IPR_BE.Models.GradedQuestion", b =>
                {
                    b.Property<int>("gradedQuestionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("gradedQuestionId"));

                    b.Property<decimal>("grade")
                        .HasColumnType("decimal(5,2)")
                        .HasColumnName("grade");

                    b.Property<long>("questionId")
                        .HasColumnType("bigint");

                    b.Property<long>("testAttempt")
                        .HasColumnType("bigint");

                    b.HasKey("gradedQuestionId");

                    b.ToTable("GradedQuestions");
                });

            modelBuilder.Entity("IPR_BE.Models.InterviewBotLog", b =>
                {
                    b.Property<int>("logId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("logId"));

                    b.Property<DateTime>("created")
                        .HasColumnType("datetime2");

                    b.Property<string>("message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("logId")
                        .HasName("logId");

                    b.ToTable("InterviewBotLogs", (string)null);
                });

            modelBuilder.Entity("IPR_BE.Models.Skill", b =>
                {
                    b.Property<int>("id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("id"));

                    b.Property<string>("name")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("id");

                    b.HasIndex("name")
                        .IsUnique();

                    b.ToTable("Skills");
                });

            modelBuilder.Entity("IPR_BE.Models.TestAttempt", b =>
                {
                    b.Property<long>("attemptId")
                        .HasColumnType("bigint");

                    b.Property<int>("candidateId")
                        .HasColumnType("int");

                    b.Property<string>("invitationUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("modifiedOn")
                        .HasColumnType("datetime2");

                    b.Property<string>("status")
                        .IsRequired()
                        .HasColumnType("varchar(20)");

                    b.Property<long>("testId")
                        .HasColumnType("bigint")
                        .HasColumnName("testId");

                    b.HasKey("attemptId")
                        .HasName("attemptId");

                    b.HasIndex("candidateId");

                    b.ToTable("TestAttempts", (string)null);
                });

            modelBuilder.Entity("CandidateSkill", b =>
                {
                    b.HasOne("IPR_BE.Models.Candidate", null)
                        .WithMany()
                        .HasForeignKey("Candidateid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("IPR_BE.Models.Skill", null)
                        .WithMany()
                        .HasForeignKey("Skillid")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("IPR_BE.Models.TestAttempt", b =>
                {
                    b.HasOne("IPR_BE.Models.Candidate", null)
                        .WithMany()
                        .HasForeignKey("candidateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
